version: '3.8'

services:
  web:
    build: .
    image: web:latest
    expose:
      - "3000"
    networks:
      - axienet

  nginx:
    image: nginx:alpine
    container_name: nginx-axietreasury
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8081:80"  
    depends_on:
      - web
    networks:
      - axienet

networks:
  axienet:
    driver: bridge
